api-charts:
  pciScope: false
  GoPolicy: false

  createDeployment: true

  createService: true

  containerPort: true

  replicaCount: 2

  container:
    image:
      repository: "docker.io/igoritosousa22/scapegoat"
      pullPolicy: IfNotPresent
      tag: "v0"
    port: 3000

  resources: {}

  service:
    type: "ClusterIP"
    port: "8000"

platform-kubearmor-policies-chart:
  matchLabels:
    app: scapegoat