k8s-helm-charts:
  createDeployment: true

  createService: true

  containerPort: true

  replicaCount: 1

  container:
    image:
      repository: "igoritosousa22/scapegoat"
      pullPolicy: IfNotPresent
      tag: "v0"
    port: "3000"

  resources: {}

  service:
    type: "ClusterIP"
    port: "80"